package xyz.wasabicodes.matlib.struct.map;

import xyz.wasabicodes.matlib.struct.MetaMaterial;
import xyz.wasabicodes.matlib.util.Version;

public class MaterialMap1_19 extends MaterialMap {

    public MaterialMap1_19() {
        // 1.20 -> 1.19
        final boolean pre3 = !Version.isVersion(19, 3);
        set("ACACIA_HANGING_SIGN", new MetaMaterial(m("ACACIA_SIGN"), false));
        set("ACACIA_WALL_HANGING_SIGN", new MetaMaterial(m("ACACIA_WALL_SIGN"), false));
        set("ANGLER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("ARCHER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("ARMS_UP_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("BAMBOO_BLOCK", new MetaMaterial(m("BIRCH_WOOD"), false));
        set("BAMBOO_BUTTON", new MetaMaterial(m("BIRCH_BUTTON"), false));
        set("BAMBOO_CHEST_RAFT", new MetaMaterial(m("BIRCH_CHEST_BOAT"), false));
        set("BAMBOO_DOOR", new MetaMaterial(m("BIRCH_DOOR"), false));
        set("BAMBOO_FENCE", new MetaMaterial(m("BIRCH_FENCE"), false));
        set("BAMBOO_FENCE_GATE", new MetaMaterial(m("BIRCH_FENCE_GATE"), false));
        set("BAMBOO_HANGING_SIGN", new MetaMaterial(m("BIRCH_SIGN"), false));
        set("BAMBOO_MOSAIC", new MetaMaterial(m("BIRCH_PLANKS"), false));
        set("BAMBOO_MOSAIC_SLAB", new MetaMaterial(m("BIRCH_SLAB"), false));
        set("BAMBOO_MOSAIC_STAIRS", new MetaMaterial(m("BIRCH_STAIRS"), false));
        set("BAMBOO_PLANKS", new MetaMaterial(m("BIRCH_PLANKS"), false));
        set("BAMBOO_PRESSURE_PLATE", new MetaMaterial(m("BIRCH_PRESSURE_PLATE"), false));
        set("BAMBOO_RAFT", new MetaMaterial(m("BIRCH_BOAT"), false));
        set("BAMBOO_SIGN", new MetaMaterial(m("BIRCH_SIGN"), false));
        set("BAMBOO_SLAB", new MetaMaterial(m("BIRCH_SLAB"), false));
        set("BAMBOO_STAIRS", new MetaMaterial(m("BIRCH_STAIRS"), false));
        set("BAMBOO_TRAPDOOR", new MetaMaterial(m("BIRCH_TRAPDOOR"), false));
        set("BAMBOO_WALL_HANGING_SIGN", new MetaMaterial(m("BIRCH_WALL_SIGN"), false));
        set("BAMBOO_WALL_SIGN", new MetaMaterial(m("BIRCH_WALL_SIGN"), false));
        set("BLADE_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("BREWER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("BRUSH", new MetaMaterial(m("GOLDEN_SHOVEL"), false));
        set("BURN_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("CALIBRATED_SCULK_SENSOR", new MetaMaterial(m("SCULK_SENSOR"), false));
        set("CAMEL_SPAWN_EGG", new MetaMaterial(m("DONKEY_SPAWN_EGG"), false));
        set("CHERRY_BOAT", new MetaMaterial(m("ACACIA_BOAT"), false));
        set("CHERRY_BUTTON", new MetaMaterial(m("ACACIA_BUTTON"), false));
        set("CHERRY_CHEST_BOAT", new MetaMaterial(m("ACACIA_CHEST_BOAT"), false));
        set("CHERRY_DOOR", new MetaMaterial(m("ACACIA_DOOR"), false));
        set("CHERRY_FENCE", new MetaMaterial(m("ACACIA_FENCE"), false));
        set("CHERRY_FENCE_GATE", new MetaMaterial(m("ACACIA_FENCE_GATE"), false));
        set("CHERRY_HANGING_SIGN", new MetaMaterial(m("ACACIA_SIGN"), false));
        set("CHERRY_LEAVES", new MetaMaterial(m("ACACIA_LEAVES"), false));
        set("CHERRY_LOG", new MetaMaterial(m("ACACIA_LOG"), false));
        set("CHERRY_PLANKS", new MetaMaterial(m("ACACIA_PLANKS"), false));
        set("CHERRY_PRESSURE_PLATE", new MetaMaterial(m("ACACIA_PRESSURE_PLATE"), false));
        set("CHERRY_SAPLING", new MetaMaterial(m("ACACIA_SAPLING"), false));
        set("CHERRY_SIGN", new MetaMaterial(m("ACACIA_SIGN"), false));
        set("CHERRY_SLAB", new MetaMaterial(m("ACACIA_SLAB"), false));
        set("CHERRY_STAIRS", new MetaMaterial(m("ACACIA_STAIRS"), false));
        set("CHERRY_TRAPDOOR", new MetaMaterial(m("ACACIA_TRAPDOOR"), false));
        set("CHERRY_WALL_HANGING_SIGN", new MetaMaterial(m("ACACIA_WALL_SIGN"), false));
        set("CHERRY_WALL_SIGN", new MetaMaterial(m("ACACIA_WALL_SIGN"), false));
        set("CHERRY_WOOD", new MetaMaterial(m("ACACIA_WOOD"), false));
        set("CHISELED_BOOKSHELF", new MetaMaterial(m("BOOKSHELF"), false));
        set("COAST_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("CRIMSON_HANGING_SIGN", new MetaMaterial(m("CRIMSON_SIGN"), false));
        set("CRIMSON_WALL_HANGING_SIGN", new MetaMaterial(m("CRIMSON_WALL_SIGN"), false));
        set("DANGER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("DARK_OAK_HANGING_SIGN", new MetaMaterial(m("DARK_OAK_SIGN"), false));
        set("DARK_OAK_WALL_HANGING_SIGN", new MetaMaterial(m("DARK_OAK_WALL_SIGN"), false));
        set("DECORATED_POT", new MetaMaterial(m("FLOWER_POT"), false));
        set("DUNE_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        if (pre3) set("ENDER_DRAGON_SPAWN_EGG", new MetaMaterial(m("BAT_SPAWN_EGG"), false));
        set("EXPLORER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("EYE_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("FRIEND_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("HEART_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("HEARTBREAK_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("HOST_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("HOWL_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        if (pre3) set("IRON_GOLEM_SPAWN_EGG", new MetaMaterial(m("SHEEP_SPAWN_EGG"), false));
        set("JUNGLE_HANGING_SIGN", new MetaMaterial(m("JUNGLE_SIGN"), false));
        set("JUNGLE_WALL_HANGING_SIGN", new MetaMaterial(m("JUNGLE_WALL_SIGN"), false));
        set("MANGROVE_HANGING_SIGN", new MetaMaterial(m("MANGROVE_SIGN"), false));
        set("MANGROVE_WALL_HANGING_SIGN", new MetaMaterial(m("MANGROVE_WALL_SIGN"), false));
        set("MINER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("MOURNER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("MUSIC_DISC_RELIC", new MetaMaterial(m("MUSIC_DISC_PIGSTEP"), false));
        set("NETHERITE_UPGRADE_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("OAK_HANGING_SIGN", new MetaMaterial(m("OAK_SIGN"), false));
        set("OAK_WALL_HANGING_SIGN", new MetaMaterial(m("OAK_WALL_SIGN"), false));
        set("PIGLIN_HEAD", new MetaMaterial(m("PLAYER_HEAD"), false));
        set("PIGLIN_WALL_HEAD", new MetaMaterial(m("PLAYER_WALL_HEAD"), false));
        set("PINK_PETALS", new MetaMaterial(m("ALLIUM"), false));
        set("PITCHER_CROP", new MetaMaterial(m("LILY_OF_THE_VALLEY"), false));
        set("PITCHER_PLANT", new MetaMaterial(m("LILY_OF_THE_VALLEY"), false));
        set("PITCHER_POD", new MetaMaterial(m("COCOA"), false));
        set("PLENTY_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("POTTED_CHERRY_SAPLING", new MetaMaterial(m("POTTED_ACACIA_SAPLING"), false));
        set("POTTED_TORCHFLOWER", new MetaMaterial(m("POTTED_RED_TULIP"), false));
        set("PRIZE_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("RAISER_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("RIB_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("SHEAF_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("SHELTER_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("SKULL_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("SNIFFER_EGG", new MetaMaterial(m("DRAGON_EGG"), false));
        set("SNIFFER_SPAWN_EGG", new MetaMaterial(m("HOGLIN_SPAWN_EGG"), false));
        set("SNORT_POTTERY_SHERD", new MetaMaterial(m("PRISMARINE_SHARD"), false));
        set("SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        if (pre3) set("SNOW_GOLEM_SPAWN_EGG", new MetaMaterial(m("SNOWBALL"), false));
        set("SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("SPRUCE_HANGING_SIGN", new MetaMaterial(m("SPRUCE_SIGN"), false));
        set("SPRUCE_WALL_HANGING_SIGN", new MetaMaterial(m("SPRUCE_WALL_SIGN"), false));
        set("STRIPPED_BAMBOO_BLOCK", new MetaMaterial(m("BIRCH_WOOD"), false));
        set("STRIPPED_CHERRY_LOG", new MetaMaterial(m("STRIPPED_ACACIA_LOG"), false));
        set("STRIPPED_CHERRY_WOOD", new MetaMaterial(m("STRIPPED_ACACIA_WOOD"), false));
        set("SUSPICIOUS_GRAVEL", new MetaMaterial(m("GRAVEL"), false));
        set("SUSPICIOUS_SAND", new MetaMaterial(m("SAND"), false));
        set("TIDE_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("TORCHFLOWER", new MetaMaterial(m("RED_TULIP"), false));
        set("TORCHFLOWER_CROP", new MetaMaterial(m("RED_TULIP"), false));
        set("TORCHFLOWER_SEEDS", new MetaMaterial(m("RED_TULIP"), false));
        set("VEX_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("WARD_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("WARPED_HANGING_SIGN", new MetaMaterial(m("WARPED_SIGN"), false));
        set("WARPED_WALL_HANGING_SIGN", new MetaMaterial(m("WARPED_WALL_SIGN"), false));
        set("WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        set("WILD_ARMOR_TRIM_SMITHING_TEMPLATE", new MetaMaterial(m("PAPER"), false));
        if (pre3) set("WITHER_SPAWN_EGG", new MetaMaterial(m("CAVE_SPIDER_SPAWN_EGG"), false));
    }

}
